apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: akhq
          env:
            - name: AKHQ_SHEMA_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: schema_registry_password
            - name: AKHQ_KAFKA_CONNECT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: connect_password
            - name: CARIOCA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: carioca_password
            - name: AKHQ_LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: ldap_bind_pwd
            - name: AKHQ_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: sasl_jaas_config
            - name: AKHQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: akhq_admin_password
            - name: AKHQ_RO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ service_id }}-secrets
                  key: akhq_ro_password